# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Karass
email: andrew.maier@gsa.gov
description: > # this means to ignore newlines until "baseurl:"
  Karass is a tool to help authors find known stakeholders for
  content types and topics that are familiar to 18F.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: andrewmaier
github_username:  andrewmaier

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

collections:
  pages:
    output: true
    permalink: /:path/
